# -*- coding: utf-8 -*-
"""consulta_rut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1borJKS81tlXQBPYZvM_8fP7AAv76TUX9
"""

import pandas as pd
from datetime import datetime
import tkinter as tk
from tkinter import filedialog, scrolledtext

def cargar_archivo():
    ruta = filedialog.askopenfilename(
        title="Selecciona el archivo Excel",
        filetypes=[("Archivos Excel", "*.xlsx *.xls")]
    )
    return ruta

def buscar_por_rut(rut, ruta_archivo):
    try:
        df = pd.read_excel(ruta_archivo, header=0)
        df.columns = [str(col).strip().upper() for col in df.columns]

        resultados = df[df['RUT'] == rut]

        if resultados.empty:
            return f"No se encontró el RUT: {rut}"

        datos = resultados.iloc[0]
        info = f"NOMBRE: {datos.get('NOMBRES', 'No disponible')}\n"
        info += f"RUT: {rut}\n"
        info += f"ESTADO: {datos.get('ESTADO', 'No disponible')}\n"
        info += f"TARJETA: {datos.get('TARJETA', 'No disponible')}\n\n"
        info += "📅 Documentos con fechas:\n"

        for columna, valor in datos.items():
            if isinstance(valor, (pd.Timestamp, datetime)):
                if pd.notna(valor):
                    info += f"{columna}: {valor.strftime('%d-%m-%Y')}\n"
            elif isinstance(valor, str):
                try:
                    fecha = pd.to_datetime(valor, errors='coerce')
                    if pd.notna(fecha):
                        info += f"{columna}: {fecha.strftime('%d-%m-%Y')}\n"
                except:
                    continue
        return info

    except Exception as e:
        return f"Error al procesar el archivo: {e}"

# --- Interfaz gráfica ---
def consultar():
    rut = entrada_rut.get().strip()
    ruta_archivo = cargar_archivo()
    if not ruta_archivo:
        cuadro_resultado.insert(tk.END, "⚠️ No se seleccionó ningún archivo.\n")
        return
    resultado = buscar_por_rut(rut, ruta_archivo)
    cuadro_resultado.delete(1.0, tk.END)
    cuadro_resultado.insert(tk.END, resultado)

# Crear ventana
ventana = tk.Tk()
ventana.title("Consulta de Documentación por RUT")
ventana.geometry("600x500")

# Campo de entrada
tk.Label(ventana, text="Ingrese RUT:").pack(pady=5)
entrada_rut = tk.Entry(ventana, width=30)
entrada_rut.pack(pady=5)

# Botón de consulta
tk.Button(ventana, text="Seleccionar archivo y consultar", command=consultar).pack(pady=10)

# Área de texto para resultados
cuadro_resultado = scrolledtext.ScrolledText(ventana, width=70, height=25)
cuadro_resultado.pack(padx=10, pady=10)

# Ejecutar ventana
ventana.mainloop()